"""ToxSynPT — synthetic PT-BR toxic-speech classification (binary).

Reference: https://huggingface.co/datasets/AKCIT/ToxSyn-PT

ToxSyn-PT ships 53,274 synthetic toxic/non-toxic PT-BR sentences with
fine-grained annotations (9 protected groups + 4 discourse types +
is_toxic binary flag). For v1 we use the binary `is_toxic` label only;
the multilabel (group × discourse) framing is a v1.1 candidate.

Complements HateBR (Instagram) and OffComBR (web/news) with a SYNTHETIC
(LLM-generated) toxic corpus. Tests whether embeddings learned on real
text generalize to LLM-synthesized adversarial examples.

License: not declared in dataset card. Recorded as "not specified"
pending author confirmation.
"""

from __future__ import annotations

from typing import Any

from mteb import TaskMetadata
from mteb.abstasks import AbsTaskClassification

_REPO = "AKCIT/ToxSyn-PT"
_REVISION = "48aac239d611"


class ToxSynPT(AbsTaskClassification):
    """ToxSyn-PT — binary toxic classification on synthetic PT-BR data."""

    metadata = TaskMetadata(
        name="ToxSynPT",
        description=(
            "Binary toxic vs non-toxic classification on AKCIT/ToxSyn-PT, a "
            "synthetic Brazilian Portuguese hate-speech corpus generated by "
            "LLMs spanning 9 protected groups (Black, Women, LGBTQIA+, etc.). "
            "Complements HateBR (Instagram) and OffComBR (web/news) with a "
            "synthetic/adversarial dimension."
        ),
        reference="https://huggingface.co/datasets/AKCIT/ToxSyn-PT",
        dataset={
            "path": _REPO,
            "revision": _REVISION,
        },
        type="Classification",
        category="t2c",
        modalities=["text"],
        eval_splits=["test"],
        eval_langs=["por-Latn"],
        main_score="accuracy",
        date=("2024-01-01", "2024-12-31"),
        domains=["Social", "Written"],
        task_subtypes=["Sentiment/Hate speech"],
        license="not specified",
        annotations_creators="LM-generated",
        dialect=["brazilian"],
        sample_creation="LM-generated and verified",
        bibtex_citation=r"""@misc{akcit-toxsyn-pt-2024,
    title = {{T}ox{S}yn-{PT}: Synthetic Brazilian Portuguese Toxicity Corpus},
    author = {{AKCIT}},
    year = {2024},
    howpublished = {\url{https://huggingface.co/datasets/AKCIT/ToxSyn-PT}},
}""",
    )

    input_column_name = "text"
    label_column_name = "is_toxic"
    samples_per_label = 32

    def dataset_transform(self, num_proc: int | None = None, **kwargs: Any) -> None:
        """ToxSyn-PT ships train/test splits with `is_toxic` boolean.

        We use them as-is; just ensure the label is encoded as ClassLabel for
        mteb's classifier-fit baselines.
        """
        assert self.dataset is not None, "load_data() must run before dataset_transform"
        if "test" in self.dataset:
            # Encode boolean -> int ClassLabel if needed
            sample_val = self.dataset["train"][0][self.label_column_name]
            if isinstance(sample_val, bool):
                from datasets import ClassLabel, DatasetDict

                cl = ClassLabel(names=["false", "true"])
                assert isinstance(self.dataset, DatasetDict)
                self.dataset = self.dataset.map(
                    lambda x: {self.label_column_name: int(bool(x[self.label_column_name]))}
                ).cast_column(self.label_column_name, cl)
